name: lint-pr-title
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title matches Conventional Commit format
        uses: lab42/conventional-commit@v0.2.0
        with:
          require_scope: "true"
          scope_regex: (\w+)
          description_regex: ([\w- ]+)
          allowed_types: |
            build
            ci
            docs
            feat
            fix
            refactor
            revert
            test
        permissions:
          pull-requests: read
