name: create-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Golang environment
        uses: actions/setup-go@v4
      - name: Build artifacts
        run: make build -o lint
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin/*
          generate_release_notes: true
          fail_on_unmatched_files: true
